
[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8080
address = "0.0.0.0"
baseUrlPath = ""
enableStaticServing = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8080
